function [R1cut,p1cut] = f1cut(in1,in2,in3)
%F1CUT
%    [R1CUT,P1CUT] = F1CUT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    16-Dec-2019 17:24:12

q42 = in1(42,:);
q43 = in1(43,:);
q44 = in1(44,:);
q45 = in1(45,:);
q46 = in1(46,:);
t2 = sin(q46);
t3 = cos(q46);
t4 = sin(q45);
t5 = cos(q45);
R1cut = reshape([t3,t2.*t4,-t2.*t5,0.0,t5,t4,t2,-t3.*t4,t3.*t5],[3,3]);
if nargout > 1
    p1cut = [q42;q43;q44];
end
