function out1 = LWRA_Position(in1,in2,in3)
%LWRA_POSITION
%    OUT1 = LWRA_POSITION(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    16-Dec-2019 17:24:04

R4cut1_1 = in3(28);
R4cut1_2 = in3(31);
R4cut1_3 = in3(34);
R4cut2_1 = in3(29);
R4cut2_2 = in3(32);
R4cut2_3 = in3(35);
R4cut3_1 = in3(30);
R4cut3_2 = in3(33);
R4cut3_3 = in3(36);
p4cut1 = in2(10);
p4cut2 = in2(11);
p4cut3 = in2(12);
q36 = in1(36,:);
q37 = in1(37,:);
q38 = in1(38,:);
t2 = cos(q36);
t3 = sin(q36);
t4 = sin(q37);
t5 = cos(q37);
t6 = R4cut1_1.*t2;
t7 = t6-R4cut1_3.*t3;
t8 = cos(q38);
t9 = sin(q38);
t10 = R4cut2_1.*t2;
t11 = t10-R4cut2_3.*t3;
t12 = R4cut3_1.*t2;
t13 = t12-R4cut3_3.*t3;
out1 = [R4cut1_2.*(-3.217920885246462e-1)+p4cut1-R4cut1_2.*t5.*2.787322377804164e-1+t4.*t7.*2.787322377804164e-1-t8.*(R4cut1_1.*t3+R4cut1_3.*t2).*4.951571951687635e-2-t9.*(R4cut1_2.*t4+t5.*t7).*4.951571951687635e-2;R4cut2_2.*(-3.217920885246462e-1)+p4cut2-R4cut2_2.*t5.*2.787322377804164e-1+t4.*t11.*2.787322377804164e-1-t8.*(R4cut2_1.*t3+R4cut2_3.*t2).*4.951571951687635e-2-t9.*(R4cut2_2.*t4+t5.*t11).*4.951571951687635e-2;R4cut3_2.*(-3.217920885246462e-1)+p4cut3-R4cut3_2.*t5.*2.787322377804164e-1+t4.*t13.*2.787322377804164e-1-t8.*(R4cut3_1.*t3+R4cut3_3.*t2).*4.951571951687635e-2-t9.*(R4cut3_2.*t4+t5.*t13).*4.951571951687635e-2];
