function out1 = RWRA_Position(in1,in2,in3)
%RWRA_POSITION
%    OUT1 = RWRA_POSITION(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    16-Dec-2019 17:24:02

R5cut1_1 = in3(37);
R5cut1_2 = in3(40);
R5cut1_3 = in3(43);
R5cut2_1 = in3(38);
R5cut2_2 = in3(41);
R5cut2_3 = in3(44);
R5cut3_1 = in3(39);
R5cut3_2 = in3(42);
R5cut3_3 = in3(45);
p5cut1 = in2(13);
p5cut2 = in2(14);
p5cut3 = in2(15);
q29 = in1(29,:);
q30 = in1(30,:);
q31 = in1(31,:);
t2 = cos(q29);
t3 = sin(q29);
t4 = sin(q30);
t5 = cos(q30);
t6 = R5cut1_1.*t2;
t7 = t6-R5cut1_3.*t3;
t8 = cos(q31);
t9 = sin(q31);
t10 = R5cut2_1.*t2;
t11 = t10-R5cut2_3.*t3;
t12 = R5cut3_1.*t2;
t13 = t12-R5cut3_3.*t3;
out1 = [R5cut1_2.*(-2.959944369991523e-1)+p5cut1-R5cut1_2.*t5.*2.613074211778332e-1+t4.*t7.*2.613074211778332e-1+t8.*(R5cut1_1.*t3+R5cut1_3.*t2).*4.642026727067356e-2+t9.*(R5cut1_2.*t4+t5.*t7).*4.642026727067356e-2;R5cut2_2.*(-2.959944369991523e-1)+p5cut2-R5cut2_2.*t5.*2.613074211778332e-1+t4.*t11.*2.613074211778332e-1+t8.*(R5cut2_1.*t3+R5cut2_3.*t2).*4.642026727067356e-2+t9.*(R5cut2_2.*t4+t5.*t11).*4.642026727067356e-2;R5cut3_2.*(-2.959944369991523e-1)+p5cut3-R5cut3_2.*t5.*2.613074211778332e-1+t4.*t13.*2.613074211778332e-1+t8.*(R5cut3_1.*t3+R5cut3_3.*t2).*4.642026727067356e-2+t9.*(R5cut3_2.*t4+t5.*t13).*4.642026727067356e-2];
