function out1 = pL5SpinalProcess_Position(in1,in2,in3)
%PL5SPINALPROCESS_POSITION
%    OUT1 = PL5SPINALPROCESS_POSITION(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Nov-2018 10:43:30

R1cut1_1 = in3(1);
R1cut1_2 = in3(4);
R1cut2_1 = in3(2);
R1cut2_2 = in3(5);
R1cut3_1 = in3(3);
R1cut3_2 = in3(6);
p1cut1 = in2(1);
p1cut2 = in2(2);
p1cut3 = in2(3);
q1 = in1(1,:);
t2 = cos(q1);
t3 = sin(q1);
out1 = [p1cut1-R1cut1_1.*t2.*6.200628630490692e-2-R1cut1_1.*t3.*2.104404980702454e-3+R1cut1_2.*t2.*2.104404980702454e-3-R1cut1_2.*t3.*6.200628630490692e-2;p1cut2-R1cut2_1.*t2.*6.200628630490692e-2-R1cut2_1.*t3.*2.104404980702454e-3+R1cut2_2.*t2.*2.104404980702454e-3-R1cut2_2.*t3.*6.200628630490692e-2;p1cut3-R1cut3_1.*t2.*6.200628630490692e-2-R1cut3_1.*t3.*2.104404980702454e-3+R1cut3_2.*t2.*2.104404980702454e-3-R1cut3_2.*t3.*6.200628630490692e-2];
